name: Build & Deploy

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_REPO: pierre-cm/prompteur
      PROMPTEUR_BASE: /prompteur-website
      PROMPTEUR_REPO: git@github.com:pierre-cm/prompteur.git
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.25
      - name: Install dependencies
        run: bun install
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          bun run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
